version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Voor het geval je aanvullende scripts hebt
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init
  build:
    commands:
      - echo Applying Terraform plan...
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Terraform apply completed on `date`

artifacts:
  files:
    - '**/*'
